<?php
$routes = [
    '' => 'HomeController@index',
    '/' => 'HomeController@index',
    '/instituicao' => 'InstituicaoController@index',
    '/laboratorios' => 'LaboratoriosController@index',
    '/noticia' => 'NoticiasController@detalhe',
    '/noticiasgerais' => 'NoticiasController@geral',
    '/noticias' => 'NoticiasController@index', 
    '/missao' => 'InstitucionalController@missao',
    '/nossotime' => 'InstitucionalController@nossotime',
    '/historico' => 'InstitucionalController@historico',
    '/estatuto' => 'InstitucionalController@estatuto',
    '/regimento' => 'InstitucionalController@regimento',
    '/certidoes' => 'InstitucionalController@certidoes',
    '/organograma' => 'InstitucionalController@organograma',
    '/credenciadas' => 'InstitucionalController@credenciadas',
    '/legislacao' => 'InstitucionalController@legislacao',
    '/credenciamento' => 'InstitucionalController@credenciamento',
    '/identidadevisual' => 'InstitucionalController@identidadevisual',
    '/contratosconvenios' => 'InstitucionalController@contratosconvenios',
    '/interveniencia' => 'InstitucionalController@interveniencia',
    '/atosnormativos' => 'InstitucionalController@atosnormativos',
    '/relatorios' => 'InstitucionalController@relatorios',
    '/itcg' => 'InstitucionalController@itcg',
    '/iacoc' => 'InstitucionalController@iacoc',
    '/noticia/{id}' => 'NoticiaController@detalhe',
    '/painel' => 'AdminController@painel',
    '/login' => 'AdminController@login',
    '/logout' => 'AdminController@logout',

    '/noticias' => 'NoticiaController@listar',
    '/noticias/pagina/{pagina}' => 'NoticiaController@listar',
    '/noticias/criar' => 'NoticiaController@criar',
    '/noticias/editar' => 'NoticiaController@editar',
    '/noticiasgerais' => 'NoticiaController@gerais',

    '/noticia/{id}' => 'NoticiaController@detalhe',
    '/noticia/{slug}/{id}' => 'NoticiaController@detalhe',

];
